version: "4"
services:
  resolver:
    build: .
    image: dns-rust:latest
    ports:
      - "58396:58396"
    network_mode: "dns"
  client:
    container_name: client
    build: .
    image: dns-rust:latest
    command: dns_rust client --server 8.8.8.8 --name example.com
  tests:
    build: 
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - coverage:/home/dns-rust/coverage/
    command: cargo test
    image: dnsrust:test

volumes:
  coverage:
    driver: local
    driver_opts:
      type: none
      device: ${PWD}/coverage/
      o: bind
