version: "4"
services:
  dns_rust:
    container_name: dns_rust
    build: .
    image: dns-rust:latest
  test:
    build: 
      context: .
    command: cargo test
    image: dns-rust:latest

volumes:
  coverage:
    driver: local
    driver_opts:
      type: none
      device: ${PWD}/coverage/
      o: bind
